version: "3.1"

services:
  redis:
    image: bitnami/redis:latest
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8082:8081

  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: gateway

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8081:8080