spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/gateway
    username: root
    password: password
  flyway:
    url: jdbc:mariadb://localhost:3306/gateway
    user: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    placeholder-replacement: false
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    cache: false
    check-template-location: false
    prefix: file:./src/main/resources/templates/
  web:
    resources.cache.period: 0
    resources.static-locations: file:./src/main/resources/static/