spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/gateway
    username: root
    password: password
  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG