spring:
  profiles:
    active: @activatedProperties@
  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
logging:
  level:
    org.springframework:
      r2dbc: DEBUG
      cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: 8080