spring:
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/gateway
    username: root
    password: password
  flyway:
    url: jdbc:mariadb://localhost:3306/gateway
    user: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
    placeholder-replacement: false
  redis:
    host: localhost
    port: 6379